name: Deploy Website to GitHub Pages

on:
  push:
    branches: [ master ]  # Changed from main
    paths:
      - 'docs/BlazorDevTools.Site.Wasm/**'
      - '.github/workflows/deploy.yml'  # Match actual filename
  workflow_dispatch:

# ... rest stays the same until:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # Changed from 8.0.x

      - name: Restore dependencies
        run: dotnet restore docs/BlazorDevTools.Site.Wasm/BlazorDevTools.Site.Wasm.csproj --ignore-failed-sources

      - name: Build
        run: dotnet build docs/BlazorDevTools.Site.Wasm/BlazorDevTools.Site.Wasm.csproj --configuration Release --no-restore /p:EnableBlazorDevToolsInProduction=true /p:EnableAutomaticMarkers=true

# ... rest stays the same